/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Balance = bigint;
export interface Category { 'id' : bigint, 'name' : string }
export interface Item { 'id' : ItemId, 'name' : string, 'price' : Balance }
export type ItemId = bigint;
export interface _SERVICE {
  'adminGrantFunds' : ActorMethod<[bigint], undefined>,
  'getAvailableItems' : ActorMethod<[], Array<Item>>,
  'getBalance' : ActorMethod<[], Balance>,
  'getCategories' : ActorMethod<[], Array<Category>>,
  'getItem' : ActorMethod<[ItemId], [] | [Item]>,
  'getOwnedItems' : ActorMethod<[], Array<ItemId>>,
  'getUserInventory' : ActorMethod<[], Array<ItemId>>,
  'initializeUser' : ActorMethod<[], undefined>,
  'purchaseItem' : ActorMethod<[ItemId], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];