/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ItemId = IDL.Nat;
export const Balance = IDL.Nat;
export const Item = IDL.Record({
  'id' : ItemId,
  'name' : IDL.Text,
  'price' : Balance,
});
export const Category = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });

export const idlService = IDL.Service({
  'adminGrantFunds' : IDL.Func([IDL.Nat], [], []),
  'getAllItems' : IDL.Func([], [IDL.Vec(Item)], ['query']),
  'getAvailableItems' : IDL.Func([], [IDL.Vec(Item)], ['query']),
  'getBalance' : IDL.Func([], [Balance], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getItem' : IDL.Func([ItemId], [IDL.Opt(Item)], ['query']),
  'getOwnedItems' : IDL.Func([], [IDL.Vec(ItemId)], ['query']),
  'getUserInventory' : IDL.Func([], [IDL.Vec(ItemId)], ['query']),
  'initializeUser' : IDL.Func([], [], []),
  'purchaseItem' : IDL.Func([ItemId], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ItemId = IDL.Nat;
  const Balance = IDL.Nat;
  const Item = IDL.Record({
    'id' : ItemId,
    'name' : IDL.Text,
    'price' : Balance,
  });
  const Category = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
  
  return IDL.Service({
    'adminGrantFunds' : IDL.Func([IDL.Nat], [], []),
    'getAllItems' : IDL.Func([], [IDL.Vec(Item)], ['query']),
    'getAvailableItems' : IDL.Func([], [IDL.Vec(Item)], ['query']),
    'getBalance' : IDL.Func([], [Balance], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getItem' : IDL.Func([ItemId], [IDL.Opt(Item)], ['query']),
    'getOwnedItems' : IDL.Func([], [IDL.Vec(ItemId)], ['query']),
    'getUserInventory' : IDL.Func([], [IDL.Vec(ItemId)], ['query']),
    'initializeUser' : IDL.Func([], [], []),
    'purchaseItem' : IDL.Func([ItemId], [], []),
  });
};

export const init = ({ IDL }) => { return []; };