/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Item {
    id: ItemId;
    name: string;
    price: Balance;
}
export type Balance = bigint;
export interface Category {
    id: bigint;
    name: string;
}
export type ItemId = bigint;
export interface backendInterface {
    adminGrantFunds(code: bigint): Promise<void>;
    getAllItems(): Promise<Array<Item>>;
    getAvailableItems(): Promise<Array<Item>>;
    getBalance(): Promise<Balance>;
    getCategories(): Promise<Array<Category>>;
    getItem(itemId: ItemId): Promise<Item | null>;
    getOwnedItems(): Promise<Array<ItemId>>;
    getUserInventory(): Promise<Array<ItemId>>;
    initializeUser(): Promise<void>;
    purchaseItem(itemId: ItemId): Promise<void>;
}
import type { Item as _Item } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async adminGrantFunds(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGrantFunds(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGrantFunds(arg0);
            return result;
        }
    }
    async getAllItems(): Promise<Array<Item>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllItems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllItems();
            return result;
        }
    }
    async getAvailableItems(): Promise<Array<Item>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableItems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableItems();
            return result;
        }
    }
    async getBalance(): Promise<Balance> {
        if (this.processError) {
            try {
                const result = await this.actor.getBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBalance();
            return result;
        }
    }
    async getCategories(): Promise<Array<Category>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategories();
            return result;
        }
    }
    async getItem(arg0: ItemId): Promise<Item | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getItem(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getItem(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOwnedItems(): Promise<Array<ItemId>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOwnedItems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOwnedItems();
            return result;
        }
    }
    async getUserInventory(): Promise<Array<ItemId>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserInventory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserInventory();
            return result;
        }
    }
    async initializeUser(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeUser();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeUser();
            return result;
        }
    }
    async purchaseItem(arg0: ItemId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.purchaseItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.purchaseItem(arg0);
            return result;
        }
    }
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Item]): Item | null {
    return value.length === 0 ? null : value[0];
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
